SELECT
    T_TAGCATEGORY.TCA_N_ID,
    T_TAGCATEGORY.TCA_CH_LABEL,
    T_TAGCATEGORY.TCA_CH_COLOR,
    T_TAG.TAG_N_ID,
    T_TAG.TAG_CH_LABEL
FROM T_TAGCATEGORY
INNER JOIN T_TAG
    ON T_TAG.TCA_N_ID = T_TAGCATEGORY.TCA_N_ID
   AND T_TAG.TAG_DT_SUPPRESSION IS NULL
WHERE T_TAGCATEGORY.TCA_DT_SUPPRESSION IS NULL
ORDER BY
    T_TAGCATEGORY.TCA_N_ORDER ASC,
    T_TAGCATEGORY.TCA_CH_LABEL ASC,
    T_TAG.TAG_N_ORDER ASC,
    T_TAG.TAG_CH_LABEL ASC
