SELECT
    T_TAG.TAG_N_ID
FROM T_TAG
INNER JOIN T_TAGCATEGORY
    ON T_TAGCATEGORY.TCA_N_ID = T_TAG.TCA_N_ID
   AND T_TAGCATEGORY.TCA_DT_SUPPRESSION IS NULL
WHERE T_TAG.TAG_DT_SUPPRESSION IS NULL
  AND T_TAG.TAG_N_ID IN (%%TAG_N_IDS%%)
