SELECT
    T_PROJECT.PRO_N_YEARSTART,
    T_PROJECT.PRO_N_YEAREND
FROM T_PROJECT
WHERE T_PROJECT.PRO_DT_SUPPRESSION IS NULL
AND
(
    T_PROJECT.PRO_N_YEARSTART IS NOT NULL
    OR T_PROJECT.PRO_N_YEAREND IS NOT NULL
)
