SELECT
    T_PROJECTTAG.PRO_N_ID,
    T_TAG.TAG_CH_LABEL,
    T_TAGCATEGORY.TCA_CH_COLOR
FROM T_PROJECTTAG
INNER JOIN T_TAG
    ON T_TAG.TAG_N_ID = T_PROJECTTAG.TAG_N_ID
   AND T_TAG.TAG_DT_SUPPRESSION IS NULL
INNER JOIN T_TAGCATEGORY
    ON T_TAGCATEGORY.TCA_N_ID = T_TAG.TCA_N_ID
   AND T_TAGCATEGORY.TCA_DT_SUPPRESSION IS NULL
WHERE T_PROJECTTAG.PTA_DT_SUPPRESSION IS NULL
ORDER BY
    T_TAGCATEGORY.TCA_N_ORDER ASC,
    T_TAG.TAG_N_ORDER ASC,
    T_TAG.TAG_CH_LABEL ASC
