SELECT
    T_PROJECT.PRO_N_ID,
    T_PROJECT.PRO_CH_LABEL,
    T_PROJECT.PRO_N_YEARSTART,
    T_PROJECT.PRO_N_YEAREND
FROM T_PROJECT
WHERE T_PROJECT.PRO_DT_SUPPRESSION IS NULL
AND NOT EXISTS
(
    SELECT 1
    FROM T_PROJECTURL
    WHERE T_PROJECTURL.PRO_N_ID = T_PROJECT.PRO_N_ID
    AND T_PROJECTURL.PRU_DT_SUPPRESSION IS NULL
)
ORDER BY
    T_PROJECT.PRO_CH_LABEL
