SELECT
    T_PROJECT.PRO_N_ID,
    T_PROJECT.PRO_CH_LABEL,
    T_PROJECT.PRO_N_YEARSTART,
    T_PROJECT.PRO_N_YEAREND
FROM T_PROJECT
WHERE T_PROJECT.PRO_DT_SUPPRESSION IS NULL
AND T_PROJECT.PRO_N_YEARSTART IS NULL
AND T_PROJECT.PRO_N_YEAREND IS NULL
ORDER BY
    T_PROJECT.PRO_CH_LABEL
