SELECT
    T_TAGCATEGORY.TCA_N_ID,
    T_TAGCATEGORY.TCA_CH_LABEL,
    T_TAGCATEGORY.TCA_N_ORDER,
    COUNT(T_PROJECT.PRO_N_ID) AS N_MISSING
FROM T_TAGCATEGORY
CROSS JOIN T_PROJECT
WHERE T_TAGCATEGORY.TCA_DT_SUPPRESSION IS NULL
AND T_PROJECT.PRO_DT_SUPPRESSION IS NULL
AND NOT EXISTS
(
    SELECT 1
    FROM T_PROJECTTAG
    INNER JOIN T_TAG
        ON T_TAG.TAG_N_ID = T_PROJECTTAG.TAG_N_ID
        AND T_TAG.TAG_DT_SUPPRESSION IS NULL
    WHERE T_PROJECTTAG.PRO_N_ID = T_PROJECT.PRO_N_ID
    AND T_PROJECTTAG.PTA_DT_SUPPRESSION IS NULL
    AND T_TAG.TCA_N_ID = T_TAGCATEGORY.TCA_N_ID
)
GROUP BY
    T_TAGCATEGORY.TCA_N_ID,
    T_TAGCATEGORY.TCA_CH_LABEL,
    T_TAGCATEGORY.TCA_N_ORDER
HAVING COUNT(T_PROJECT.PRO_N_ID) > 0
ORDER BY
    T_TAGCATEGORY.TCA_N_ORDER,
    T_TAGCATEGORY.TCA_CH_LABEL
