SELECT
    T_PROJECT.PRO_N_ID,
    T_PROJECT.PRO_CH_LABEL,
    T_PROJECT.PRO_N_YEARSTART,
    T_PROJECT.PRO_N_YEAREND
FROM T_PROJECT
WHERE T_PROJECT.PRO_DT_SUPPRESSION IS NULL
AND NOT EXISTS
(
    SELECT 1
    FROM T_PROJECTTAG
    INNER JOIN T_TAG
        ON T_TAG.TAG_N_ID = T_PROJECTTAG.TAG_N_ID
        AND T_TAG.TAG_DT_SUPPRESSION IS NULL
    WHERE T_PROJECTTAG.PRO_N_ID = T_PROJECT.PRO_N_ID
    AND T_PROJECTTAG.PTA_DT_SUPPRESSION IS NULL
    AND T_TAG.TCA_N_ID = %%TCA_N_ID%%
)
ORDER BY
    T_PROJECT.PRO_CH_LABEL
