SELECT
    T_TAGCATEGORY.TCA_N_ID,
    T_TAGCATEGORY.TCA_CH_LABEL,
    T_TAGCATEGORY.TCA_CH_COLOR,
    T_TAGCATEGORY.TCA_N_ORDER
FROM T_TAGCATEGORY
WHERE T_TAGCATEGORY.TCA_DT_SUPPRESSION IS NULL
ORDER BY
    T_TAGCATEGORY.TCA_N_ORDER ASC,
    T_TAGCATEGORY.TCA_CH_LABEL ASC
