SELECT
    T_PROJECTFILE.PRF_N_ID,
    T_PROJECTFILE.PRF_BL_SEARCHIMAGE
FROM T_PROJECTFILE
WHERE T_PROJECTFILE.PRO_N_ID = %%PRO_N_ID%%
  AND T_PROJECTFILE.PRF_DT_SUPPRESSION IS NULL
  AND T_PROJECTFILE.PRF_CH_MIMETYPE LIKE 'image/%'
FOR UPDATE
