SELECT
    T_PROJECTURL.PRU_N_ID,
    T_PROJECTURL.PRU_N_ORDER
FROM T_PROJECTURL
WHERE T_PROJECTURL.PRO_N_ID = %%PRO_N_ID%%
  AND T_PROJECTURL.PRU_DT_SUPPRESSION IS NULL
ORDER BY
    T_PROJECTURL.PRU_N_ORDER ASC,
    T_PROJECTURL.PRU_N_ID ASC
