SELECT
    T_PROJECTFILE.PRF_N_ID,
    T_PROJECTFILE.PRF_N_ORDER
FROM T_PROJECTFILE
WHERE T_PROJECTFILE.PRO_N_ID = %%PRO_N_ID%%
  AND T_PROJECTFILE.PRF_DT_SUPPRESSION IS NULL
ORDER BY
    T_PROJECTFILE.PRF_N_ORDER ASC,
    T_PROJECTFILE.PRF_N_ID ASC
