SELECT
    T_USER.USR_N_ID,
    T_USER.USR_CH_LOGIN,
    T_USER.USR_CH_PASSWORD
FROM T_USER
WHERE T_USER.USR_DT_SUPPRESSION IS NULL
  AND LOWER(T_USER.USR_CH_LOGIN) = LOWER(%%USR_CH_LOGIN%%)
ORDER BY T_USER.USR_N_ID DESC
LIMIT 1
