SELECT
    T_PROJECT.PRO_N_ID,
    T_PROJECT.PRO_CH_LABEL,
    T_PROJECT.PRO_CH_DESCRIPTION,
    T_PROJECT.PRO_N_YEARSTART,
    T_PROJECT.PRO_N_YEAREND
FROM T_PROJECT
WHERE T_PROJECT.PRO_N_ID = %%PRO_N_ID%%
  AND T_PROJECT.PRO_DT_SUPPRESSION IS NULL
