SELECT
    T_PROJECTFILE.PRF_N_ID,
    T_PROJECTFILE.FTY_N_ID,
    T_PROJECTFILE.PRF_CH_LABEL,
    T_PROJECTFILE.PRF_CH_FILENAME,
    T_PROJECTFILE.PRF_CH_MIMETYPE,
    T_PROJECTFILE.PRF_N_SIZE,
    T_PROJECTFILE.PRF_N_YEAR,
    T_PROJECTFILE.PRF_BL_SEARCHIMAGE
FROM T_PROJECTFILE
WHERE T_PROJECTFILE.PRO_N_ID = %%PRO_N_ID%%
  AND T_PROJECTFILE.PRF_DT_SUPPRESSION IS NULL
ORDER BY
    T_PROJECTFILE.PRF_N_ORDER ASC,
    T_PROJECTFILE.PRF_N_ID ASC
