SELECT
    T_PROJECTFILE.PRF_N_ID
FROM T_PROJECTFILE
WHERE T_PROJECTFILE.PRO_N_ID = %%PRO_N_ID%%
  AND T_PROJECTFILE.PRF_DT_SUPPRESSION IS NULL
  AND T_PROJECTFILE.PRF_CH_MIMETYPE LIKE 'image/%'
ORDER BY
    T_PROJECTFILE.PRF_N_ORDER ASC,
    T_PROJECTFILE.PRF_N_ID ASC
LIMIT 1
