SELECT
    T_PROJECTURL.PRO_N_ID,
    T_PROJECTURL.PRU_CH_URL,
    T_PROJECTURL.PRU_CH_LABEL,
    T_PROJECTURL.PRU_N_YEAR
FROM T_PROJECTURL
WHERE T_PROJECTURL.PRU_N_ID = %%PRU_N_ID%%
  AND T_PROJECTURL.PRU_DT_SUPPRESSION IS NULL
