CREATE TABLE IF NOT EXISTS T_USER (
    USR_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USR_CH_LOGIN VARCHAR(255) NOT NULL,
    USR_CH_PASSWORD VARCHAR(255) NOT NULL,
    USR_N_MID INT UNSIGNED NULL,
    USR_DT_CREATION DATETIME NOT NULL,
    USR_CH_CREATION VARCHAR(255) NOT NULL,
    USR_DT_SUPPRESSION DATETIME NULL,
    USR_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (USR_N_ID),
    INDEX IDX_T_USER_LOGIN (USR_CH_LOGIN),
    INDEX IDX_T_USER_MID (USR_N_MID),
    INDEX IDX_T_USER_SUPPRESSION (USR_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_PROJECT (
    PRO_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRO_CH_LABEL VARCHAR(255) NOT NULL,
    PRO_CH_DESCRIPTION TEXT NULL,
    PRO_N_YEARSTART SMALLINT UNSIGNED NULL,
    PRO_N_YEAREND SMALLINT UNSIGNED NULL,
    PRO_N_MID INT UNSIGNED NULL,
    PRO_DT_CREATION DATETIME NOT NULL,
    PRO_CH_CREATION VARCHAR(255) NOT NULL,
    PRO_DT_SUPPRESSION DATETIME NULL,
    PRO_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (PRO_N_ID),
    INDEX IDX_T_PROJECT_YEARSTART (PRO_N_YEARSTART),
    INDEX IDX_T_PROJECT_YEAREND (PRO_N_YEAREND),
    INDEX IDX_T_PROJECT_MID (PRO_N_MID),
    INDEX IDX_T_PROJECT_SUPPRESSION (PRO_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_TAGCATEGORY (
    TCA_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TCA_CH_LABEL VARCHAR(255) NOT NULL,
    TCA_CH_COLOR VARCHAR(50) NOT NULL,
    TCA_N_ORDER INT NOT NULL DEFAULT 0,
    TCA_N_MID INT UNSIGNED NULL,
    TCA_DT_CREATION DATETIME NOT NULL,
    TCA_CH_CREATION VARCHAR(255) NOT NULL,
    TCA_DT_SUPPRESSION DATETIME NULL,
    TCA_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (TCA_N_ID),
    INDEX IDX_T_TAGCATEGORY_ORDER (TCA_N_ORDER),
    INDEX IDX_T_TAGCATEGORY_MID (TCA_N_MID),
    INDEX IDX_T_TAGCATEGORY_SUPPRESSION (TCA_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_TAG (
    TAG_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TCA_N_ID INT UNSIGNED NOT NULL,
    TAG_CH_LABEL VARCHAR(255) NOT NULL,
    TAG_N_ORDER INT NOT NULL DEFAULT 0,
    TAG_N_MID INT UNSIGNED NULL,
    TAG_DT_CREATION DATETIME NOT NULL,
    TAG_CH_CREATION VARCHAR(255) NOT NULL,
    TAG_DT_SUPPRESSION DATETIME NULL,
    TAG_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (TAG_N_ID),
    INDEX IDX_T_TAG_CATEGORY (TCA_N_ID),
    INDEX IDX_T_TAG_ORDER (TAG_N_ORDER),
    INDEX IDX_T_TAG_MID (TAG_N_MID),
    INDEX IDX_T_TAG_SUPPRESSION (TAG_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_PROJECTTAG (
    PTA_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRO_N_ID INT UNSIGNED NOT NULL,
    TAG_N_ID INT UNSIGNED NOT NULL,
    PTA_N_MID INT UNSIGNED NULL,
    PTA_DT_CREATION DATETIME NOT NULL,
    PTA_CH_CREATION VARCHAR(255) NOT NULL,
    PTA_DT_SUPPRESSION DATETIME NULL,
    PTA_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (PTA_N_ID),
    INDEX IDX_T_PROJECTTAG_PROJECT (PRO_N_ID),
    INDEX IDX_T_PROJECTTAG_TAG (TAG_N_ID),
    INDEX IDX_T_PROJECTTAG_MID (PTA_N_MID),
    INDEX IDX_T_PROJECTTAG_SUPPRESSION (PTA_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_URLTYPE (
    UTY_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    UTY_CH_LABEL VARCHAR(255) NOT NULL,
    UTY_N_MID INT UNSIGNED NULL,
    UTY_DT_CREATION DATETIME NOT NULL,
    UTY_CH_CREATION VARCHAR(255) NOT NULL,
    UTY_DT_SUPPRESSION DATETIME NULL,
    UTY_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (UTY_N_ID),
    INDEX IDX_T_URLTYPE_MID (UTY_N_MID),
    INDEX IDX_T_URLTYPE_SUPPRESSION (UTY_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_PROJECTURL (
    PRU_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRO_N_ID INT UNSIGNED NOT NULL,
    UTY_N_ID INT UNSIGNED NOT NULL,
    PRU_CH_URL VARCHAR(2000) NOT NULL,
    PRU_CH_LABEL VARCHAR(255) NULL,
    PRU_N_YEAR SMALLINT UNSIGNED NULL,
    PRU_N_ORDER INT NOT NULL DEFAULT 0,
    PRU_N_MID INT UNSIGNED NULL,
    PRU_DT_CREATION DATETIME NOT NULL,
    PRU_CH_CREATION VARCHAR(255) NOT NULL,
    PRU_DT_SUPPRESSION DATETIME NULL,
    PRU_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (PRU_N_ID),
    INDEX IDX_T_PROJECTURL_PROJECT (PRO_N_ID),
    INDEX IDX_T_PROJECTURL_TYPE (UTY_N_ID),
    INDEX IDX_T_PROJECTURL_ORDER (PRU_N_ORDER),
    INDEX IDX_T_PROJECTURL_MID (PRU_N_MID),
    INDEX IDX_T_PROJECTURL_SUPPRESSION (PRU_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_FILETYPE (
    FTY_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FTY_CH_LABEL VARCHAR(255) NOT NULL,
    FTY_N_MID INT UNSIGNED NULL,
    FTY_DT_CREATION DATETIME NOT NULL,
    FTY_CH_CREATION VARCHAR(255) NOT NULL,
    FTY_DT_SUPPRESSION DATETIME NULL,
    FTY_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (FTY_N_ID),
    INDEX IDX_T_FILETYPE_MID (FTY_N_MID),
    INDEX IDX_T_FILETYPE_SUPPRESSION (FTY_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS T_PROJECTFILE (
    PRF_N_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRO_N_ID INT UNSIGNED NOT NULL,
    FTY_N_ID INT UNSIGNED NOT NULL,
    PRF_CH_LABEL VARCHAR(255) NULL,
    PRF_CH_FILENAME VARCHAR(255) NOT NULL,
    PRF_CH_MIMETYPE VARCHAR(255) NOT NULL,
    PRF_N_SIZE BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRF_CH_PATH VARCHAR(2000) NOT NULL,
    PRF_CH_SOURCE VARCHAR(20) NULL,
    PRF_CH_SOURCE_URL TEXT NULL,
    PRF_N_YEAR SMALLINT UNSIGNED NULL,
    PRF_N_ORDER INT NOT NULL DEFAULT 0,
    PRF_BL_SEARCHIMAGE TINYINT(1) NOT NULL DEFAULT 0,
    PRF_N_MID INT UNSIGNED NULL,
    PRF_DT_CREATION DATETIME NOT NULL,
    PRF_CH_CREATION VARCHAR(255) NOT NULL,
    PRF_DT_SUPPRESSION DATETIME NULL,
    PRF_CH_SUPPRESSION VARCHAR(255) NULL,
    PRIMARY KEY (PRF_N_ID),
    INDEX IDX_T_PROJECTFILE_PROJECT (PRO_N_ID),
    INDEX IDX_T_PROJECTFILE_TYPE (FTY_N_ID),
    INDEX IDX_T_PROJECTFILE_ORDER (PRF_N_ORDER),
    INDEX IDX_T_PROJECTFILE_SEARCHIMAGE (PRO_N_ID, PRF_BL_SEARCHIMAGE),
    INDEX IDX_T_PROJECTFILE_MID (PRF_N_MID),
    INDEX IDX_T_PROJECTFILE_SUPPRESSION (PRF_DT_SUPPRESSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
