SELECT
    T_PROJECTFILE.PRO_N_ID,
    T_PROJECTFILE.PRF_N_ID
FROM T_PROJECTFILE
WHERE T_PROJECTFILE.PRF_DT_SUPPRESSION IS NULL
  AND T_PROJECTFILE.PRF_BL_SEARCHIMAGE = 1
  AND T_PROJECTFILE.PRF_CH_MIMETYPE LIKE 'image/%'
