SELECT
    T_PROJECT.PRO_N_ID,
    T_PROJECT.PRO_CH_LABEL,
    T_PROJECT.PRO_CH_DESCRIPTION,
    T_PROJECT.PRO_N_YEARSTART,
    T_PROJECT.PRO_N_YEAREND
FROM T_PROJECT
WHERE T_PROJECT.PRO_DT_SUPPRESSION IS NULL
%%SEARCH_FILTER%%
%%YEAR_FILTER%%
%%TAG_FILTER%%
ORDER BY
    T_PROJECT.PRO_N_YEARSTART DESC,
    T_PROJECT.PRO_CH_LABEL ASC
