SELECT DISTINCT
    T_TAGCATEGORY.TCA_N_ID,
    T_TAGCATEGORY.TCA_CH_LABEL,
    T_TAG.TAG_N_ID,
    T_TAG.TAG_CH_LABEL
FROM T_TAGCATEGORY
INNER JOIN T_TAG
    ON T_TAG.TCA_N_ID = T_TAGCATEGORY.TCA_N_ID
   AND T_TAG.TAG_DT_SUPPRESSION IS NULL
INNER JOIN T_PROJECTTAG
    ON T_PROJECTTAG.TAG_N_ID = T_TAG.TAG_N_ID
   AND T_PROJECTTAG.PTA_DT_SUPPRESSION IS NULL
INNER JOIN T_PROJECT
    ON T_PROJECT.PRO_N_ID = T_PROJECTTAG.PRO_N_ID
   AND T_PROJECT.PRO_DT_SUPPRESSION IS NULL
WHERE T_TAGCATEGORY.TCA_DT_SUPPRESSION IS NULL
ORDER BY
    T_TAGCATEGORY.TCA_N_ORDER ASC,
    T_TAGCATEGORY.TCA_CH_LABEL ASC,
    T_TAG.TAG_N_ORDER ASC,
    T_TAG.TAG_CH_LABEL ASC
